### ISSUE TITLE
Need to make 'storage' directory before running inference

### ISSUE THREAD

**Issue by pottsj21** [ketatam/DiffDock-PP#16]
When running `src/inference.sh` with the `single_pair_inference` config file provided, I get this error:
```
Traceback (most recent call last):
  File "/home/DiffDock-PP/src/main_inf.py", line 620, in <module>
    main()
  File "/home/DiffDock-PP/src/main_inf.py", line 354, in main
    dump_predictions(args,results)
  File "/home/DiffDock-PP/src/main_inf.py", line 383, in dump_predictions
    with open(args.prediction_storage, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'storage/single_pair_run.pkl'
```
Simply create a 'storage' directory before running `inference.sh`, or `mkdir` (if the dir doesn't exist) somewhere in `main_inf.py`

**Comment by jh2ee** [comment]
If you run DiffDock in conda environment, you can successfully get a result. Or you have to check your python. Add PATH or ECHO

**Comment by aggelos-michael-papadopoulos** [comment]
Or simply add this line before the "echo"s in inference.sh (or db5_inference.sh):
mkdir -p storage  # Ensure the storage directory exists
